name: Publish to Dropbox

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download all release assets
        uses: softprops/action-download-release-asset@v1
        with:
          repository: sadigitalforce/strassengeschichte
          tag: ${{ github.ref_name }}
          asset_name: '*'

      - name: Upload to Dropbox
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: |
          for f in *; do
            echo "Uploading $f..."
            curl -X POST https://content.dropboxapi.com/2/files/upload \
              --header "Authorization: Bearer $DROPBOX_TOKEN" \
              --header "Dropbox-API-Arg={\"path\": \"/VERLAGSPROJEKTE_SA_AXMANN/strassengeschichte/$f\", \"mode\": \"overwrite\"}" \
              --header "Content-Type: application/octet-stream" \
              --data-binary @"$f"
          done
