name: Publish ZIP to Dropbox (Direct)

on:
  push:
    paths:
      - release-assets/**

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload ZIP(s) from release-assets to Dropbox
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: |
          echo "Starte Upload aus release-assets/..."
          shopt -s nullglob
          for f in release-assets/*.zip; do
            echo "Hochladen von $f..."
            curl -X POST https://content.dropboxapi.com/2/files/upload \
              --header "Authorization: Bearer $DROPBOX_TOKEN" \
              --header "Dropbox-API-Arg: {\"path\": \"/VERLAGSPROJEKTE_SA_AXMANN/strassengeschichte/$(basename $f)\",\"mode\": \"overwrite\"}" \
              --header "Content-Type: application/octet-stream" \
              --data-binary @$f
          done

