name: Upload Release to Dropbox

on:
  workflow_dispatch:    # Manuelles Auslösen über „Run workflow“ in Actions
  release:             # Automatisches Auslösen beim Veröffentlichen eines Releases
    types:
      - published
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download release asset
        uses: dawidd6/action-download-release-asset@v3
        with:
          repository: ${{ github.repository }}
          tag:        ${{ github.event.release.tag_name }}
          asset_name: 'Band1_Full_Package.zip'
          output:     './Band1_Full_Package.zip'

      - name: Upload to Dropbox
        uses: peter-evans/dropbox-upload@v2
        with:
          access-token:    ${{ secrets.DROPBOX_TOKEN }}
          destination-path: '/Straßengeschichte/Band1_Full_Package.zip'
          source-file:      './Band1_Full_Package.zip'
