name: Upload Release to Dropbox

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:

      # 1) Hol dir das Repo (brauchen wir für das GH-CLI)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Installiere jq (für JSON-Parsen)
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # 3) Lade das Release-Asset via GitHub-API
      - name: Download release asset via API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Asset-Name anpassen:
          ASSET_NAME='Band1_Full_Package.zip'

          # Hol dir die Asset-ID
          ASSET_ID=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${GITHUB_REF##*/} \
            | jq -r --arg NAME "$ASSET_NAME" '.assets[] | select(.name == $NAME) | .id')

          if [ -z "$ASSET_ID" ]; then
            echo "Asset $ASSET_NAME nicht gefunden!"
            exit 1
          fi

          # Download-Link ermitteln und herunterladen
          curl -L -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/octet-stream" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/assets/$ASSET_ID \
            -o "./$ASSET_NAME"

      # 4) Upload per curl in deine Dropbox
      - name: Upload to Dropbox via curl
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: |
          ASSET_NAME='Band1_Full_Package.zip'
          curl -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer $DROPBOX_TOKEN" \
            --header "Dropbox-API-Arg: {\"path\": \"/Strassengeschichte/$ASSET_NAME\",\"mode\": \"overwrite\",\"mute\": false}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @./"$ASSET_NAME"
