jobs:
   upload:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3

-      - name: Download release asset
-        uses: dawidd6/action-download-release-asset@v2
+      - name: Download release asset
+        uses: dawidd6/action-download-release-asset@v1

       - name: Upload to Dropbox
-        uses: peter-evans/dropbox-upload@v1
+        uses: peter-evans/dropbox-upload@v2
